version: '2'
services:
    iris-app:
        image: iris
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://iris-mysql:3306/iris?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 80:80
    iris-mysql:
        extends:
            file: mysql.yml
            service: iris-mysql
